### ISSUE TITLE
TG-26: Operations by authenticated principals on notes

### ISSUE THREAD

**Issue by sebasruii** [sebasruii/Acme-L3-D03#7]
26) Operations by authenticated principals on notes:

§ List the notes that are not older than one month and show their details.

§ Post a note. This operation requires confirmation because notes cannot be updated or de-leted.

**Comment by joaquin-restoy** [comment]
8

**Comment by sebasruii** [comment]
8

**Comment by Lucperrom** [comment]
7

**Comment by mariams73** [comment]
7
